# .github/workflows/build-and-push.yml
name: Build, Sign, and Push DDEV Webserver Image
on:
  push:
    branches:
      - main # Trigger on push to main branch
  workflow_dispatch: # Allows manual trigger
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR
      id-token: write # Required for Cosign OIDC integration (keyless signing)
      security-events: write # Required for github/codeql-action/upload-sarif to upload results
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Just
        uses: extractions/setup-just@v2
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: just build
      - name: Tag, sign, scan and push image
        run: just push
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif # Path to the SARIF file generated by Trivy
          category: image-vulnerability-scan # Optional: Helps categorize the results in GitHub UI
