# .github/workflows/build-and-push.yml
name: Build, Sign, and Push DDEV Webserver Image
# Builds hardened Apache+PHP-FPM image, scans for vulnerabilities, signs with Cosign, and pushes to GHCR
on:
  push:
    branches:
      - main # Trigger on push to main branch
  workflow_dispatch: # Allows manual trigger
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR
      id-token: write # Required for Cosign OIDC integration (keyless signing)
      security-events: write # Required for github/codeql-action/upload-sarif to upload results
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and run in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/wagov-dtt/apache-fpm-webserver
          runCmd: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            just build
            just push
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif # Path to the SARIF file generated by Trivy
          category: image-vulnerability-scan # Optional: Helps categorize the results in GitHub UI
